/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Utilizzo = IDL.Record({
  'apparecchiatura' : IDL.Text,
  'data' : IDL.Int,
  'luogo' : IDL.Text,
  'tecnico' : IDL.Text,
  'kgUsati' : IDL.Float64,
});
export const Bombola = IDL.Record({
  'gasResiduoKg' : IDL.Float64,
  'utilizzi' : IDL.Vec(Utilizzo),
  'taraKg' : IDL.Float64,
  'tipoGas' : IDL.Text,
  'codice' : IDL.Text,
  'gasTotaleKg' : IDL.Float64,
  'produttore' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBombola' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'addTestData' : IDL.Func([], [], []),
  'bombolaExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteBombola' : IDL.Func([IDL.Text], [], []),
  'getAllBombole' : IDL.Func([], [IDL.Vec(Bombola)], ['query']),
  'getBombola' : IDL.Func([IDL.Text], [Bombola], ['query']),
  'registerUtilizzo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Utilizzo = IDL.Record({
    'apparecchiatura' : IDL.Text,
    'data' : IDL.Int,
    'luogo' : IDL.Text,
    'tecnico' : IDL.Text,
    'kgUsati' : IDL.Float64,
  });
  const Bombola = IDL.Record({
    'gasResiduoKg' : IDL.Float64,
    'utilizzi' : IDL.Vec(Utilizzo),
    'taraKg' : IDL.Float64,
    'tipoGas' : IDL.Text,
    'codice' : IDL.Text,
    'gasTotaleKg' : IDL.Float64,
    'produttore' : IDL.Text,
  });
  
  return IDL.Service({
    'addBombola' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'addTestData' : IDL.Func([], [], []),
    'bombolaExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'deleteBombola' : IDL.Func([IDL.Text], [], []),
    'getAllBombole' : IDL.Func([], [IDL.Vec(Bombola)], ['query']),
    'getBombola' : IDL.Func([IDL.Text], [Bombola], ['query']),
    'registerUtilizzo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };